### ISSUE TITLE
verify boiler control for case study

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/obc#121]
For the case study, ensure that pumps start at minimum speed, and the boiler should likely also start at the minimum firing rate (of say 20 to 30%). Below is a plot that shows that these start with `y=1`:

![image](https://user-images.githubusercontent.com/1329080/168683329-519e157a-5418-46cd-9001-4ce4820f5bb2.png)

Also, it looks incorrect that the boiler cycles, but is never operated at part load.

The figure was simulated with
```
simulateModel("SystemModel.Validation.System", stopTime=43200, method="Cvode", tolerance=1e-06, resultFile="System");
```
using commit 0e00d31ed75f6568058865c9b3047ae36e547fdf

**Comment by mwetter** [comment]
@karthikeyad-pnnl: can you please look into how to correct this and make a pull request.

**Comment by karthikeyad-pnnl** [comment]
> @karthikeyad-pnnl: can you please look into how to correct this and make a pull request.

@mwetter : I have some ideas about how to change the logic. I will make the appropriate changes by the end of this week.

**Comment by karthikeyad-pnnl** [comment]
@mwetter : I have implemented changes to the logic to resolve the issues mentioned here. They have got coupled with some previous changes on PR #123. Please let me know if you would like me to submit these changes through a separate PR.

**Comment by karthikeyad-pnnl** [comment]
@mwetter:  Can we close this issue since required changes have been merged into [branch](https://github.com/lbl-srg/obc/tree/issue92_caseStudyFullHVAC) through [commit](https://github.com/lbl-srg/obc/pull/123/commits/f55f3ab1b0e0e13833c12d40151aaba9244e268a)?
