### ISSUE TITLE
expand replaceable description

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/obc#153]
@mwetter In point 4 of #151 I had in mind the following rules for the constraining type from https://specification.modelica.org/maint/3.6/inheritance-modification-and-redeclaration.html#constraining-type

> In a replaceable declaration the optional constraining-clause defines a constraining type. Any modifications following the constraining type name are applied both for the purpose of defining the actual constraining type and they are automatically applied in the declaration and in any subsequent redeclaration. The precedence order is that declaration modifiers override constraining type modifiers.

> If the constraining-clause is not present in the original declaration (i.e., the non-redeclared declaration):
• The type of the declaration is also used as a constraining type.
• The modifiers for subsequent redeclarations and constraining type are the modifiers on the component or short-class-definition if that is used in the original declaration, otherwise empty.

It may be worth mentioning these rules and perhaps providing an example such as the one in #151.

_Originally posted by @AntoineGautier in https://github.com/lbl-srg/obc/issues/152#issuecomment-2310159947_

**Comment by mwetter** [comment]
@AntoineGautier : I am not sure the example that you provided is valid: OpenModelica errors at
https://github.com/lbl-srg/obc/commit/6c79251b8d709509c755e775e73df50ed62214cd#diff-9333fa8b01feb8cee629d1e68ca198e82637e4291bee2a14741c0c6308c915fcR13
because a `final` binding is overridden, which I don't think is valid. If the example is meant to explain the precedence, shouldn't we remove the `final` modifier?

**Comment by AntoineGautier** [comment]
@mwetter This is intended, see the inline comment of the declaration that causes the error:
```mo
  Model component1(redeclare Record rec);  // Overriding by param=param from the constraining clause: Dymola errors, OCT evaluates to 2.
```
If you remove this declaration, the model should be successfully translated by OMC.
I think it's sometimes useful to include incorrect constructs in examples to illustrate complicated logic. But feel free to remove it if you find it too confusing.
