### ISSUE TITLE
Add vendor annotation description to 6.8. Annotations in cdl.rst

### ISSUE THREAD

**Issue by milicag** [lbl-srg/obc#2]
Vendor annotation is related to point-to-point specification and tagging. Update documentation to contain a description of the preferable tagging concept based on the information obtained from the project partners.

Updates:
from Michael: Please make the tagging proposal in terms of a specification in https://github.com/lbl-srg/obc/blob/master/specification/source/cdl.rst
from Brent: see email thread

**Comment by mwetter** [comment]
@milicag Please also add an example with description at https://github.com/lbl-srg/obc/blob/master/specification/source/cdl.rst, which should become the standardization document once we agreed on an implementation.

**Comment by mwetter** [comment]
This has been added to the master.
