### ISSUE TITLE
Edit plotting notebook

### ISSUE THREAD

**Issue by milicag** [lbl-srg/obc#21]
Per Brent's suggestion:

- [x] reorder so that G36 and baseline are on the same image, put seasons on different plots.
- [x] add Fahrenheit indicator

**Comment by mwetter** [comment]
Please make a new branch based on `issue20_case_study1`

**Comment by milicag** [comment]
@mwetter The code that is currently on  ```issue20_case_study1``` case study branch generates plots that look as these:
![flow_signals_all](https://user-images.githubusercontent.com/5322943/31971661-99a98a78-b8d1-11e7-8294-021a420f7e93.png)
![tahu_all](https://user-images.githubusercontent.com/5322943/31971663-9bebea1a-b8d1-11e7-8c36-8d18d55f3aa7.png)

It is not straight forward how to reduce the white space between certain and not all subplots, so I've, for the sake of simplicity, decided to run them by you first.

**Comment by milicag** [comment]
Done.
